title: "selfdriven Education"
description: "Research & Frameworks to help commununities self-actate"
context: "education"
repo: "selfdriven-education"
baseurl: ""
url: ""
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: default
plugins:
  - jekyll-feed
  - jekyll-seo-tag
